name: Python Syntax Check

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  syntax-check:
    name: Check Python Syntax
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the Python version you want to use

    - name: Install dependencies
      run: pip install -r requirements.txt  # Modify if needed

    - name: Check syntax
      uses: ms-pyright/pyright@v0
      with:
        args: check --outputjson .

