name: Python Syntax Check

on:
  push:
    branches:
      - main

jobs:
  syntax-check:
    name: Check Python Syntax
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Choose an appropriate Node.js version

    - name: Install pyright
      run: npm install -g pyright

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the Python version you want to use

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check Python syntax
      run: pyright
