name: Python Syntax Check

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  syntax-check:
    name: Check Python Syntax
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14  # Choose a suitable Node.js version

    - name: Install Pyright
      run: npm install -g pyright

    - name: Check Python syntax
      run: pyright
