name: Python Syntax Check

on:
  push:
    branches:
      - main

jobs:
  syntax-check:
    name: Check Python Syntax
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the Python version you want to use

    - name: Set up a virtual environment
      run: python -m venv venv
    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check Python syntax
      run: pyright
